# -*- coding: utf-8 -*-
"""NLP _Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEl2DzdMTGMAOrgPCZrbCWYaPQKzQpfx

# NLP-Based Customer Query Intent Classification and Automatic Routing

### Mini Project using CLINC150 Dataset

**Objective:**  
To develop an NLP-based system that automatically identifies the intent of a customer's query and routes the query to the appropriate support service.

**NLP Technique:** TF-IDF

**Machine Learning Models:**
- Logistic Regression
- Multinomial Naive Bayes

**Evaluation Metrics:**
- Accuracy
- Precision
- Recall
- F1-Score
- Confusion Matrix

## 1. Project Overview

Customer support systems receive a large number of text-based queries every day.
Manually identifying the purpose of each query can be time-consuming.

This project uses Natural Language Processing (NLP) and machine learning to automatically classify customer queries into predefined intent categories.

The system first preprocesses the text, converts it into numerical features using TF-IDF, and then uses machine learning models to predict the customer's intent.

The predicted intent is finally mapped to an appropriate support service.

## 2. Import Required Libraries
"""

import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

"""## 3. Dataset Loading"""

from google.colab import files

uploaded = files.upload()

with open("data_full.json", "r") as file:
    data = json.load(file)

print(data.keys())

"""### Create DataFrames"""

train_df = pd.DataFrame(
    data["train"],
    columns=["text", "intent"]
)

val_df = pd.DataFrame(
    data["val"],
    columns=["text", "intent"]
)

test_df = pd.DataFrame(
    data["test"],
    columns=["text", "intent"]
)

print("Training samples:", len(train_df))
print("Validation samples:", len(val_df))
print("Testing samples:", len(test_df))

"""## 4. Dataset Exploration"""

print("Sample training data:")
train_df.head()

intents = sorted(train_df["intent"].unique())

print("Number of intents:", len(intents))

print("\nAll available intents:")

for i, intent in enumerate(intents, 1):
    print(i, intent)

intent_counts = train_df["intent"].value_counts()

print("Number of examples for each intent:")
print(intent_counts)

"""## 5. Intent Selection"""

selected_intents = [
    "book_flight",
    "book_hotel",
    "flight_status",
    "lost_luggage",
    "restaurant_reservation",
    "restaurant_suggestion",
    "weather",
    "car_rental",
    "travel_suggestion",
    "directions"
]

print("Selected intents:")

for i, intent in enumerate(selected_intents, 1):
    print(i, intent)

"""### Why these intents?

Ten travel and customer-assistance intents were selected from CLINC150 to create a focused and manageable multi-class NLP classification problem.

The selected intents cover flight booking, hotel booking, flight status, baggage problems, restaurants, weather, transportation, travel planning, and navigation.

## 6. Dataset Preparation
"""

train_selected = train_df[
    train_df["intent"].isin(selected_intents)
].copy()

print("Training samples:", len(train_selected))
print("\nTraining class distribution:")
print(train_selected["intent"].value_counts())

val_selected = val_df[
    val_df["intent"].isin(selected_intents)
].copy()

print("Validation samples:", len(val_selected))
print("\nValidation class distribution:")
print(val_selected["intent"].value_counts())

test_selected = test_df[
    test_df["intent"].isin(selected_intents)
].copy()

print("Test samples:", len(test_selected))
print("\nTest class distribution:")
print(test_selected["intent"].value_counts())

"""### Separate Input and Target Variables"""

X_train = train_selected["text"]
y_train = train_selected["intent"]

X_val = val_selected["text"]
y_val = val_selected["intent"]

X_test = test_selected["text"]
y_test = test_selected["intent"]

print("Training text:", X_train.shape)
print("Training labels:", y_train.shape)

print("Testing text:", X_test.shape)
print("Testing labels:", y_test.shape)

"""## 7. Text Preprocessing"""

import re

def preprocess_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

example = "I WANT to BOOK a Flight!!! Can you help me?"

print("Original:")
print(example)

print("\nAfter preprocessing:")
print(preprocess_text(example))

X_train_clean = X_train.apply(preprocess_text)
X_val_clean = X_val.apply(preprocess_text)
X_test_clean = X_test.apply(preprocess_text)

print("\nOriginal dataset example:")
print(X_train.iloc[0])

print("\nAfter preprocessing:")
print(X_train_clean.iloc[0])

"""## 8. TF-IDF Feature Extraction"""

vectorizer = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

X_train_tfidf = vectorizer.fit_transform(X_train_clean)
X_val_tfidf = vectorizer.transform(X_val_clean)
X_test_tfidf = vectorizer.transform(X_test_clean)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Validation TF-IDF shape:", X_val_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

"""TF-IDF converts the cleaned customer queries into numerical feature vectors that can be processed by machine learning algorithms.

The vectorizer is fitted only on the training data and then used to transform the validation and test data.

## 9. Model 1 — Logistic Regression
"""

logistic_model = LogisticRegression(
    max_iter=1000
)

logistic_model.fit(X_train_tfidf, y_train)

print("Logistic Regression model trained successfully!")

y_pred_lr = logistic_model.predict(X_test_tfidf)

print("First 10 predictions:")
print(y_pred_lr[:10])

lr_accuracy = accuracy_score(y_test, y_pred_lr)

print(
    "Logistic Regression Accuracy:",
    round(lr_accuracy * 100, 2),
    "%"
)

print("Logistic Regression Classification Report")

print(
    classification_report(
        y_test,
        y_pred_lr,
        target_names=selected_intents
    )
)

"""## 10. Model 2 — Multinomial Naive Bayes"""

nb_model = MultinomialNB()

nb_model.fit(X_train_tfidf, y_train)

print("Naive Bayes model trained successfully!")

y_pred_nb = nb_model.predict(X_test_tfidf)

print("First 10 Naive Bayes predictions:")
print(y_pred_nb[:10])

nb_accuracy = accuracy_score(y_test, y_pred_nb)

print(
    "Naive Bayes Accuracy:",
    round(nb_accuracy * 100, 2),
    "%"
)

print("Naive Bayes Classification Report")

print(
    classification_report(
        y_test,
        y_pred_nb,
        target_names=selected_intents
    )
)

"""## 11. Model Comparison"""

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Multinomial Naive Bayes"
    ],
    "Accuracy (%)": [
        lr_accuracy * 100,
        nb_accuracy * 100
    ]
})

results

plt.figure(figsize=(8, 5))

plt.bar(
    results["Model"],
    results["Accuracy (%)"]
)

plt.title("Model Accuracy Comparison")
plt.xlabel("Machine Learning Model")
plt.ylabel("Accuracy (%)")
plt.ylim(0, 100)

plt.show()

"""## 12. Confusion Matrix"""

cm = confusion_matrix(
    y_test,
    y_pred_lr,
    labels=selected_intents
)

plt.figure(figsize=(12, 10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=selected_intents,
    yticklabels=selected_intents
)

plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted Intent")
plt.ylabel("Actual Intent")

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""## 13. Custom Customer Query Prediction"""

def predict_intent(query):

    # Preprocess the query
    cleaned_query = preprocess_text(query)

    # Convert the query into TF-IDF features
    query_tfidf = vectorizer.transform([cleaned_query])

    # Predict the intent
    prediction = logistic_model.predict(query_tfidf)[0]

    return prediction

# Test with a new customer query

query = "I want to book a flight to Delhi"

predicted_intent = predict_intent(query)

print("Customer Query:", query)
print("Predicted Intent:", predicted_intent)

"""## 14. Automatic Query Routing"""

routing_map = {
    "book_flight": "Flight Booking Support",
    "book_hotel": "Hotel Booking Support",
    "flight_status": "Flight Status Support",
    "lost_luggage": "Baggage Support",
    "restaurant_reservation": "Restaurant Reservation Support",
    "restaurant_suggestion": "Restaurant Recommendation Service",
    "weather": "Weather Information Service",
    "car_rental": "Car Rental Support",
    "travel_suggestion": "Travel Planning Support",
    "directions": "Navigation Support"
}

# Complete query classification and routing

def classify_and_route(query):

    predicted_intent = predict_intent(query)

    department = routing_map[predicted_intent]

    print("Customer Query:", query)
    print("Predicted Intent:", predicted_intent)
    print("Suggested Route:", department)

# Test the complete system

classify_and_route("My luggage is missing after my flight")

"""## 15. Final System Demonstration"""

# Test multiple customer queries

test_queries = [
    "I need to book a flight",
    "Can you help me reserve a hotel?",
    "Is my flight delayed?",
    "My luggage is missing",
    "I want to reserve a table at a restaurant",
    "Can you suggest a good restaurant?",
    "What is the weather today?",
    "I need to rent a car",
    "Suggest a good place to travel",
    "How do I get to the airport?"
]

for query in test_queries:
    classify_and_route(query)
    print("-" * 50)

"""## 16. Conclusion

This project demonstrates how Natural Language Processing can be used to automatically classify customer queries into predefined intent categories.

The system uses text preprocessing and TF-IDF feature extraction followed by Logistic Regression and Multinomial Naive Bayes classification.

The models are evaluated using accuracy, precision, recall, F1-score, and a confusion matrix.

The final system also demonstrates automatic routing of customer queries to the appropriate support service based on the predicted intent.
"""